# Site settings
title: Mihir Khadilkar
email: mikhadil@uni-mainz.de
description: > # this means to ignore newlines until "baseurl:"
    Personal website of Mihir Khadilkar, a postdoctoral researcher at University of Mainz, Germany.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  mihirkh

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Postdoctoral Researcher"
excerpt_separator: "<!--more-->"

# Google services
google_analytics: UA-86881194-1
# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""

gems:
  - jekyll-seo-tag
